spring.application.name=ApiGateway
server.port=8080

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway Routes

# ProductService: Routes /products/*/*
spring.cloud.gateway.routes[0].id=productservicemapping
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/*/*
spring.cloud.gateway.routes[0].uri=lb://productservice

# UserService: Routes /users/*
spring.cloud.gateway.routes[1].id=userservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/*
spring.cloud.gateway.routes[1].uri=lb://user-service

# OrderService: Routes /orders/*
spring.cloud.gateway.routes[2].id=orderservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/*
spring.cloud.gateway.routes[2].uri=lb://orderservice

# PaymentService: Routes /pay/*
spring.cloud.gateway.routes[3].id=paymentservice
spring.cloud.gateway.routes[3].predicates[0]=Path=/pay/*
spring.cloud.gateway.routes[3].uri=lb://paymentservice

# EmailService does not expose REST APIs (Kafka-based) — no route needed

# Enable actuator
management.endpoints.web.exposure.include=*
